server:
  port: 8082 # Puerto único para este servicio

spring:
  application:
    name: service-b # Nombre con el que se registrará en Eureka (¡IMPORTANTE!)
  datasource:
    url: jdbc:mysql://localhost:3306/db_service_b?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true # Base de datos diferente
    username: micro_user
    password: micro_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # O 'create'
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL del servidor Eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,info