apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-service-b-init
  namespace: microservices
data:
  init.sql: |
    -- Coloca aquí el contenido de tu archivo init-service-b.sql
    CREATE TABLE IF NOT EXISTS orders (
                                          id INT AUTO_INCREMENT PRIMARY KEY,
                                          product_id INT NOT NULL,
                                          quantity INT NOT NULL,
                                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );