apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-service-a
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-service-a
  template:
    metadata:
      labels:
        app: mysql-service-a
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: root-password
            - name: MYSQL_DATABASE
              value: "db_service_a"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
          volumeMounts:
            - name: mysql-service-a-data
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-service-a-data
          persistentVolumeClaim:
            claimName: mysql-service-a-pvc
        - name: init-script
          configMap:
            name: mysql-service-a-init
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-a
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-service-a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-service-a-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi