apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-service-a-init
  namespace: microservices
data:
  init.sql: |
    # Aquí debes colocar el contenido de tu archivo init-service-a.sql
    # Por ejemplo:
    CREATE TABLE IF NOT EXISTS products (
                                            id INT AUTO_INCREMENT PRIMARY KEY,
                                            name VARCHAR(255) NOT NULL,
        price DECIMAL(10,2) NOT NULL,
        description TEXT
        );