server:
  port: 8081

spring:
  application:
    name: service-a
  datasource:
    url: jdbc:mysql://mysql-service-a:3306/db_service_a?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: micro_user
    password: micro_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,info
