apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      imagePullSecrets:
        - name: ocirsecret
      containers:
        - name: service-a
          image: sa-bogota-1.ocir.io/axv8ixlpasy5/service-a:2025-05-17-303
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: microservices
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: service-a